[theme]
primaryColor = "#1E90FF"

[theme.textStyles]
textInput = """
<style>
div[data-baseweb="input"] > div:focus-within {
    border-color: #1E90FF !important;
    box-shadow: 0 0 0 1px #1E90FF !important;
}
</style>
""" 